_full_stack: &full_stack
  services:
    - postgresql
    - redis
  addons:
    postgresql: "9.6"
  before_script:
    - psql --version
    - psql -U postgres -c 'SELECT version();'
    - psql -U postgres -c 'create database nautobot;'

env:
  - INVOKE_LOCAL=True
os:
  - linux
dist: focal
language: python
before_install:
  - pip install poetry
install:
  - poetry config virtualenvs.create false
  # Poetry 1.1.0 added parallel installation as an option;
  # unfortunately it seems to have some issues with installing/updating "requests" and "certifi"
  # while simultaneously atttempting to *use* those packages to install other packages.
  # For now we disable it.
  - poetry config installer.parallel false
  - poetry install

script:
  - invoke $TEST

stages:
  - Linting
jobs:
  fast_finish: true
  allow_failures:
    - python: "3.9"
  include:
    - name: Black
      python: "3.6"
      script: invoke black
    - name: Flake8
      python: "3.6"
      script: invoke flake8
    - name: Check Migrations
      python: "3.6"
      <<: *full_stack
      script: "invoke make-migrations"
    - name: Unit Tests (Python 3.6)
      python: "3.6"
      <<: *full_stack
      script: "invoke unittest"
    - name: Unit Tests (Python 3.7)
      python: "3.7"
      <<: *full_stack
      script: "invoke unittest"
    - name: Unit Tests (Python 3.8)
      python: "3.8"
      <<: *full_stack
      script: "invoke unittest"
    - name: Unit Tests (Python 3.9)
      python: "3.9"
      <<: *full_stack
      script: "invoke unittest"
