# Generated by Django 3.1.7 on 2021-03-28 00:46

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('_base_group', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.group')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
